apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice1
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 50
    scaleUp:
      stabilizationWindowSeconds: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 180
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 180