alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    additionalAlertRelabelConfigs: []
    additionalAlertManagerConfigs: []
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
  serviceMonitor:
    relabelings:
      - targetLabel: cluster
        replacement: cluster-1
