server:
  port: 1025

management:
  server:
    port: 1026
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, prometheus
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}

tracing:
  url: http://production-collector.observability.svc.cluster.local:4317


spring:
  application:
    name: microservice1

security:
  ignored: /**

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


grpc:
  client:
    microservice2:
      address: microservice2.default.svc.cluster.local:1025
      negotiationType: plaintext


