apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice2
    job: microservice2
  name: microservice2
spec:
  ports:
    - name: http
      port: 1026
      protocol: TCP
      targetPort: 1026
    - name: https
      port: 1025
      protocol: TCP
      targetPort: 1025
  selector:
    app.kubernetes.io/name: microservice2
  type: ClusterIP
