apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: microservice2-selfsigned-certificate
  namespace: default
spec:
  keystores:
    jks:
      passwordSecretRef:
        name: jks-password-secret
        key: password
      create: true
  issuerRef:
    name: selfsigned-issuer
    group: cert-manager.io
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - microservice2.default.svc.cluster.local
  secretName: microservice2-selfsigned-certificate
  commonName: microservice2.default.svc.cluster.local
